### ISSUE TITLE
Client side crash

### ISSUE THREAD

**Issue by Dragoragoda** [Jacob-Mango/DayZ-CommunityOnlineTools#103]
I was able to replicate a crash.

This crash can be replicated with a hatchet or similar size weapon in your hand. if you join a server and have just cf and community online tools installed and then die while a weapon or item of similar size to a hatchet in your hands you then respawn. When you respawn and move you crash to desktop with status violation

if i remove cf and community online it does not happen. if i have these enabled and die with nothing in my hands i do not crash on respawn. if i die with a steak knife or combat knife i do not crash. but if i have a rifle, hatchet, axe, shovel, or any medium to large size weapon or item in my hand i crash to desktop after respawning.

**Comment by LieutenantMaster** [comment]
Cant reproduce anymore, taking it as fixed
