### ISSUE TITLE
Two Issues; relocating vehicles and free cam

### ISSUE THREAD

**Issue by Vin-267** [Jacob-Mango/DayZ-CommunityOnlineTools#113]
Relocating Vehicles:
- When attempting to manually relocate a vehicle (click object drop down box, modify coordinates, move to coordinate) the vehicle does not actually move in game. At least not visually. The vehicle becomes bugged, where the interactive prompt appears but you are unable to actually interact with it. When the server restarts the vehicle respawns in the location it was moved to.

Free Cam:
- Unable to determine in game cause, but sometimes when attempting to go into freecam mode it moves extremely slow, like inches per minute.

Server: Fragnet server

Mod list:
- CF
- Community-Online-Tools
- Trader
- BuildAnywhere_v3
- VanillaPlusPlusMap
- Banking
- BaseBuildingPlus
- Code Lock
- Breachingcharge
- SchanaModCompass
- Unlimited Stamina
- Saline Bag+
- GoreZ
- Base Fortifications
- BulletStacksPlusPlus
- BetterSuppressors
- Ear-Plugs
- SchanaModParty
- FlipTransport
- KillFeed
- MuchStuffPack
- SchanaModGlobalChat
- MunghardsItempack
- FIDOv PACK 4
- Airdrop-Upgraded
- ToxicZone
- FS (FIDOv STALKER)
- Gold Nuggets
- Heroes And Bandits
- Gerphelius Zil-130
- No-Vehicle-Damage
- Admin Pack
- WindstridesClothingPack
- No Shoe Damage
- SIX-DayZ-Auto-Run
- Mass'sManyItemOverhaul
- MRAP 4x4
- Modular Vest System
- CannabisPlus
- Base Furniture Mods 3.0

**Comment by das-heimchen** [comment]
FreeCam: Noticed that too. Issue rose after scrolling to object spawn list.
You can use your mousewheel to increase and decrease the movement speed of freecam.

**Comment by LieutenantMaster** [comment]
Fixed
