### ISSUE TITLE
Can we get these warnings fixed, please?

### ISSUE THREAD

**Issue by Celdritch** [Jacob-Mango/DayZ-CommunityOnlineTools#115]
SCRIPT    (W): @"JM/COT/Scripts/3_Game/communityonlinetools\config\configentry.c,163": Missing ';' at the end of line
SCRIPT    (W): @"JM/COT/Scripts/3_Game/communityonlinetools\config\configclass.c,256": Missing ';' at the end of line
SCRIPT    (W): @"JM/COT/Scripts/4_World/communityonlinetools\classes\staticfunctions.c,81": Missing ';' at the end of line
SCRIPT    (W): @"JM/COT/Scripts/4_World/communityonlinetools\entities\itembase\basebuildingbase.c,38": Missing ';' at the end of line
SCRIPT    (W): @"JM/COT/Scripts/4_World/communityonlinetools\entities\itembase\basebuildingbase.c,46": Missing ';' at the end of line
SCRIPT    (W): @"JM/COT/Scripts/4_World/communityonlinetools\classes\cotmodule.c,180": Missing ';' at the end of line
SCRIPT    (W): @"JM/COT/Scripts/4_World/communityonlinetools\classes\webhook\jmwebhookmessage.c,10": Missing ';' at the end of line
SCRIPT    (W): @"JM/COT/Scripts/4_World/communityonlinetools\classes\webhook\jmwebhookconstructor.c,22": Missing ';' at the end of line
SCRIPT    (W): @"JM/COT/Scripts/4_World/communityonlinetools\classes\webhook\jmwebhookconnectiongroup.c,56": Missing ';' at the end of line
SCRIPT    (W): @"JM/COT/Scripts/5_Mission/communityonlinetools\modules\esp\jmespmodule.c,177": Unsafe down-casting, use 'JMESPViewType.Cast' for safe down-casting

**Comment by LieutenantMaster** [comment]
fixed
