### ISSUE TITLE
0xC0000005 = STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by ghost** [Jacob-Mango/DayZ-CommunityOnlineTools#122]
I've been working on this for hours, everytime I start browsing weapons the game crashes with this error. Anyone else have the same error? Any solutions??

**Comment by EA-One** [comment]
solution : untick the tick which does say : "enable item preview" or "showcase" i dunno which of them . but ur game is crashing because it has to load all the pictures that fast. So disableing helps at my site . i guess its because of that , never found another senseful reason . . .

**Comment by ghost** [comment]
And where would that be?

**Comment by EA-One** [comment]
> And where would that be?

somewhere in the item menu , or next to the items

**Comment by chowley0623** [comment]
I can't find either of those options, I'm in game in the COT menu

**Comment by ghost** [comment]
> > And where would that be?
> 
> somewhere in the item menu , or next to the items

I cant find that, are you in game or in server files? Can you upload an image? Also it only appears to happen when I click on certain weapons.

**Comment by LieutenantMaster** [comment]
fixed
