### ISSUE TITLE
ObjectManagerScroll => GameCrash

### ISSUE THREAD

**Issue by Silgir** [Jacob-Mango/DayZ-CommunityOnlineTools#123]
If you scroll up and down in the object manager, the game crashes ..... this error does not occur with any of the other admin tools. (For this reason, expansion has unfortunately flown from our servers.)

**Comment by VariatoX** [comment]
Can confirm that issue too with the current and previous builds. 

Edit: Maybe add an **checkbox** for deactivating the preview of the selected item which should be checked (preview disabled by default)? That seems to be the issue. Script tries to load an invalid item.

**Comment by TheHunterGT** [comment]
Same issue as above.  Scrolling through the weapons list with the mouse wheel crashes the game.

**Comment by salutesh** [comment]
Problem is that when ever you click on a object in the list that has no model the engine crashes because it cant create its item preview. Just dont click on items, objects and base classes that come up in the list and it will not crash. Its almost impossible to filter out all these objects and remove them. Way to much effort unless somone want to sit down and get all the class names.

**Comment by grupobritto** [comment]
"QuickieBow",
		"GP25Base",
		"GP25",
		"GP25_Standalone",
		"M203Base",
		"M203",
		"M203_Standalone",
		"Red9",
		"LargeTentBackPack",
		"ItemOptics",

I tested it now and only with these did the game close. Some items are not ready (showing flashes) but do not close the game.

**Comment by salutesh** [comment]
> 
> 
> ```
> 	"QuickieBow",
> 	"GP25Base",
> 	"GP25",
> 	"GP25_Standalone",
> 	"M203Base",
> 	"M203",
> 	"M203_Standalone",
> 	"Red9",
> 	"LargeTentBackPack",
> 	"ItemOptics",
> ```
> 
> I tested it now and only with these did the game close. Some items are not ready (showing flashes) but do not close the game.

This is a good start!

**Comment by LieutenantMaster** [comment]
fixed
