### ISSUE TITLE
Object Spawner - Items despawning

### ISSUE THREAD

**Issue by mikedehaan** [Jacob-Mango/DayZ-CommunityOnlineTools#124]
Items created with the Object Spawner seem to have a very low lifetime set. Vehicles and other items brought in using the tool will disappear when the player is out of range (approx. 50m) for 2-5min.

**Comment by Lemon-B-Citrom** [comment]
Running into a similar issue, especially noticeable with vehicles. Even those in perfect condition, not missing any wheels, not parked precariously, and with items in inventory will despawn when a player is out of distance for long enough.

**Comment by thedevouttrout** [comment]
i ran into this issue last night, lost 90% of my gear and food

**Comment by LieutenantMaster** [comment]
Configure your server mpmission (xml files) items and they wont despawn
