### ISSUE TITLE
Items spawning in the ground

### ISSUE THREAD

**Issue by blackbeard68** [Jacob-Mango/DayZ-CommunityOnlineTools#125]
Good afternoon, 

When trying to use the item spawner to spawn in the Merlin Heli or Huey they spawn in mostly in the ground.  But if I spawn in the Baby bird it spawns in on the ground but if I get in the cockpit it all goes black! Any ideas?  Is it a new bug? Help! ;)

**Comment by LieutenantMaster** [comment]
Fixed
