### ISSUE TITLE
GForce Now showing as VPN

### ISSUE THREAD

**Issue by jackpotmonkey** [Jacob-Mango/DayZ-CommunityOnlineTools#126]
I was directed towards this mod as being the source of GForce now users being unable to connect to modded servers as they are detected as using a VPN (previously the ip blocks used by gforcenow was whitelisted but that seems to have changed). Not sure if you are able to whitelist them again but i thought it was worth a try as nvidia cant address the issue due to how the program works.

**Comment by LieutenantMaster** [comment]
Not COT related
