### ISSUE TITLE
NULL pointer to instance  Class:      'JMESPMetaPlayer' Function: 'UpdateActions'

### ISSUE THREAD

**Issue by Gufalagupagup** [Jacob-Mango/DayZ-CommunityOnlineTools#127]
Game crashes sometimes when I'm using ESP Tools. Also some players around the area started to crash.

`NULL pointer to instance
Class:      'JMESPMetaPlayer'
Function: 'UpdateActions'
Stack trace:
JM/COT/Scripts/5_Mission/communityonlinetools\modules\esp\jmespmeta.c:235
JM/COT/Scripts/5_Mission/communityonlinetools\modules\esp\jmespmeta.c:54
JM/COT/Scripts/5_Mission/communityonlinetools\modules\esp\jmespmodule.c:286
scripts/3_Game/dayzgame.c:2388
DayZExpansion/Core/3_Game/dayzexpansion_core\dayzgame.c:156`

Thanks!

**Comment by LieutenantMaster** [comment]
Fixed
