### ISSUE TITLE
COT Not Updating Expansion Files

### ISSUE THREAD

**Issue by SnkyFrsh** [Jacob-Mango/DayZ-CommunityOnlineTools#129]
Have found that I have to manually edit the Dayz Expansion files manually to apply settings as using COT while in-game the settings do not apply.

If I select an option and hit apply it does nothing, hitting refresh after clears the selection.

Unsure of how to get around this other than manually editing ExpansionMod/Settings/

Permissions are fine as everything else in COT works fine, outside of Expansion

My load order is 
`@CF; @Community-Online-Tools;@DayZ-Expansion-Licensed;  @DayZ-Expansion-Core; @Dayz-Expansion;   @Dayz-Expansion-Vehicles; - then the rest of my mods`

**Comment by salutesh** [comment]
This is more a expansion related issue as these Modules for COT are within the Expansion Main mod.
In general switching and applying the settings in the setting Modules should work.
