### ISSUE TITLE
Multiple Issues after Update 1.13 | Spectating, ESP, Invisible, Repair Tranport

### ISSUE THREAD

**Issue by DerSani1988** [Jacob-Mango/DayZ-CommunityOnlineTools#131]
After the July 13th update I noticed following issues:

**1) Spectating not working anymore**
If I open the Player Management, select an user and click on "spectate" the observation cam is below the map or black and not really moving or sometimes nothing happens after clicking the button
![Image of Spectating](https://share.iandy.tv/7qSYZA.png)

**2) ESP Tool Radius is not working properly**
If I open the ESP Tool, select an Item, set the radius below 100 meters, eg 10 meters, and click on "show" object are shown up to 100 meters.
![Image of ESP](https://share.iandy.tv/3Tr89g.jpg)

**3) Invisibility not working / not available**
If I open the Player Management, select an user there is no option to make me invisible, even if the right in permissions is granted.
![Image of Player options](https://share.iandy.tv/3Qscur.png)

**4) Repair Transport is not working anymore**
If I open the Player Management, select an user and click on "Repair Transport" nothing happens and the Vehicle is still damaged or broken.

Environment Details:

**[Specs]**
**DayZ Version:** v1.13.154025
**COT Version:** 13 Jul @ 12:53pm

**[Tested on]**
**Server 1 Mods:** 

>`@CF`
> `@ZomBerry Admin Tools`
> `@Community-Online-Tools`
> `@Ear-Plugs`
> `@Gas-Pump-Refueling`
> `@Code Lock`
> `@Airdrop-Upgraded`
> `@[Remastered] Arma Weapon Pack`
> `@KOD Weapons`
> `@WindstridesClothingPack`
> `@VanillaPlusPlusMap`
> `@Trolley Kart`
> `@Trader`
> `@MunghardsItempack`
> `@BaseBuildingPlus`
> `@Mass'sManyItemOverhaul`
> `@BuildAnywhere_v3`
> `@MuchStuffPack`

**Server 2 Mods:** 

>`@CF`
> `@ZomBerry Admin Tools`
> `@Community-Online-Tools`
> `@Ear-Plugs`

**Comment by LieutenantMaster** [comment]
fixed
