### ISSUE TITLE
Can't compile mission init script'!

### ISSUE THREAD

**Issue by EvilAnimal** [Jacob-Mango/DayZ-CommunityOnlineTools#132]
I've been looking for a couple hours for this issue. Hopefully someone can help me out. I'm running the server on a PC at home with CF Tools. Trying to get expansion.deerisle to startup but get this error below.

Crashlog
Can't compile mission init script'!

$CurrentDir:mpmissions\Expansion.DeerIsle\init.c(39): Can't find variable 'ExpansionObjectSpawnTools'

Runtime mode
CLI params: config serverDZ.cfg.active port 2302 profiles profiles adminlog  freezecheck  dologs  mod @CF;@Community-Online-Tools;@DayZ-Expansion;@DayZ-Expansion-Core;@DayZ-Expansion-Vehicles;@DayZ-Expansion-Licensed;

**Comment by salutesh** [comment]
You use the wrong Mission files.
You try to use the latest Expansion Experimental mission files what will not work with the current Stable Expansion Mods.
Use these files instead: https://github.com/ExpansionModTeam/DayZ-Expansion-Missions/releases/tag/1.5.1245-1.13

**Comment by EvilAnimal** [comment]
Thank you!

**Comment by salutesh** [comment]
Ticket can be closed i guess 👍
