### ISSUE TITLE
Player AI ESP confusing players and AI

### ISSUE THREAD

**Issue by Chi-Yu** [Jacob-Mango/DayZ-CommunityOnlineTools#135]
NPCs show up under the **Players** filter, not **Player AI**.

They will have the "Player" overlay and apparently show the data of an actual player (myself in this case).

Maybe something changed in the way how the ESP module differs between the two. I saw some weird casting based checks. Maybe something can now be cast which couldn't be cast before and the `isValid()` method no longer does what it's supposed to do.

I'm also confused as to why the AI filter is in the steam workshop while the code is apparently only in the development branch. I thought the Steam workshop would have the "production" branch.

**Comment by LieutenantMaster** [comment]
Fixed
