### ISSUE TITLE
Remove diseases on heal

### ISSUE THREAD

**Issue by Chi-Yu** [Jacob-Mango/DayZ-CommunityOnlineTools#138]
I modded `JMPlayerModule` in our server mod and added a call to `player.RemoveAllAgents()` in `Exec_Heal()` in an attempt to also cure diseases (primarily chemical poisoning which is kinda hard to get rid of).

This appears to do what I hoped it would do in terms of removing the disease "agents" which in turn appears to cause the game scripts to take care of removing or resetting the associated properties like symptoms, player modifiers, etc.

Symptoms which are already queued up will still run though as far as I can tell, so if the player is already about to vomit, removing the agent alone probably won't cancel that.

I'm not even 100% certain that this is the "right" way to do this due to the lack of documentation from BI but maybe it's better than having a heal button which doesn't actually heal everything?

**Comment by LieutenantMaster** [comment]
Should be implemented with the latest update now
