### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by PrestonVeals** [Jacob-Mango/DayZ-CommunityOnlineTools#141]
---------------------------------------------
Log C:\Program Files (x86)\Steam\steamapps\common\DayZServer\profiles\crash_2021-12-23_13-49-11.log started at 23.12. 19:53:03

------------------------------------
WIN-IVM8KDQICB1, 23.12 2021 19:53:03
NULL pointer to instance
Class:      'JMModuleManager'
Function: '~JMModuleManager'
Stack trace:
JM/COT/Scripts/4_World/communityonlinetools\classes\module\jmmodulemanager.c:14

Runtime mode
CLI params: config serverDZ.cfg port 1776 profiles C:\Program Files (x86)\Steam\steamapps\common\DayZServer\profiles mod @Deerisle;@CF;@Community-Online-Tools;@Dabs;@DayZ-Expansion;@DayZ-Expansion-Book;@DayZ-Expansion-Core;@DayZ-Expansion-Licensed;@DayZ-Expansion-Vehicles;@Stamin;@WeaponReduxPack 

------------------------------------
WIN-IVM8KDQICB1, 23.12 2021 19:53:03
NULL pointer to instance
Class:      'JMPlayerModule'
Function: '~JMPlayerModule@314#14'
Stack trace:
JM/COT/Scripts/5_Mission/communityonlinetools\modules\player\jmplayermodule.c:69

Runtime mode
CLI params: config serverDZ.cfg port 1776 profiles C:\Program Files (x86)\Steam\steamapps\common\DayZServer\profiles mod @Deerisle;@CF;@Community-Online-Tools;@Dabs;@DayZ-Expansion;@DayZ-Expansion-Book;@DayZ-Expansion-Core;@DayZ-Expansion-Licensed;@DayZ-Expansion-Vehicles;@Stamin;@WeaponReduxPack 

------------------------------------
WIN-IVM8KDQICB1, 23.12 2021 19:53:03
NULL pointer to instance
Class:      'COTModule'
Function: '~COTModule'
Stack trace:
JM/COT/Scripts/4_World/communityonlinetools\classes\cotmodule.c:22

Runtime mode
CLI params: config serverDZ.cfg port 1776 profiles C:\Program Files (x86)\Steam\steamapps\common\DayZServer\profiles mod @Deerisle;@CF;@Community-Online-Tools;@Dabs;@DayZ-Expansion;@DayZ-Expansion-Book;@DayZ-Expansion-Core;@DayZ-Expansion-Licensed;@DayZ-Expansion-Vehicles;@Stamin;@WeaponReduxPack

**Comment by LieutenantMaster** [comment]
Fixed
