### ISSUE TITLE
Scripted variables corrupted upon ... !

### ISSUE THREAD

**Issue by Oneleg3** [Jacob-Mango/DayZ-CommunityOnlineTools#146]
Hi!

I was doing some testing on the experimental branch of DayZ, 1.17 it is now I believe, and I was running into memory allocation issues on init. When looking through the logs it seemed to be caused by an error being spammed

```
"!!! Scripted variables corrupted upon "Sneakers_Green"
 7:47:57 !!! Scripted variables corrupted upon "Rangefinder"
 7:47:57 !!! Scripted variables corrupted upon "MetalWire"
 7:47:57 !!! Scripted variables corrupted upon "Netting"
 7:47:57 !!! Scripted variables corrupted upon "MiniDress_WhiteChecker"
 7:47:57 !!! Scripted variables corrupted upon "StartKitIV"
 7:47:57 !!! Scripted variables corrupted upon "CanOpener"
 7:47:57 !!! Scripted variables corrupted upon "DirtBikeHelmet_Mouthguard"
 7:47:57 !!! Scripted variables corrupted upon "Ammo_12gaSlug"
 7:47:57 !!! Scripted variables corrupted upon "BarbedWire"
 7:47:57 !!! Scripted variables corrupted upon "MetalWire"
 7:47:57 !!! Scripted variables corrupted upon "CivSedanDoors_BackRight_WhiteRust"
 7:47:57 !!! Scripted variables corrupted upon "WorkingBoots_Beige"
 7:47:57 !!! Scripted variables corrupted upon "SteakKnife"
 7:47:57 !!! Scripted variables corrupted upon "HunterPants_Winter"
 7:47:57 !!! Scripted variables corrupted upon "PolicePantsOrel""
```

The error "Scripted variables" etc etc -- lists for every individual item in the game. After stripping away all of the mods we use, I was left with just CF, and COT. So I had to deduce the problem is somewhere in COT as it would need to index all of the items for the spawn menu. If by some weird chance this turns out to be CF, my apologies, but I couldn't get anything further than this from RPT, or crash logs.

note: I can get the server to start with just CF and COT and ignore these errors, however adding any other mods back becomes too much for the init process to handle, alongside all of these errors.

**Comment by LieutenantMaster** [comment]
Unrelated to COT, this is probably due to CF Storage being disabled by removing a mod enabling it (judging by the date of your message, I assume CF)
