### ISSUE TITLE
Player List Performance Issues

### ISSUE THREAD

**Issue by Thimeri0n** [Jacob-Mango/DayZ-CommunityOnlineTools#147]
When you open the player list, or perform any action that triggers the player list being loaded (like enabling ESP) it will only load about 5 players ever few seconds and your client is completely desynced until the full list is loaded.
On servers with more than 20 or so people this is extremely noticeable, when we where using COT with 80 slots sometimes it could take upwards of 30s to load the full player list.
Subsequently switched to VPP and noticed a marked performance increase for server FPS while also not suffering issues when loading the player list.

**Comment by LieutenantMaster** [comment]
Should be fixed by now
