### ISSUE TITLE
Issue with Vehicle spawner in 4k

### ISSUE THREAD

**Issue by SomeoneElsexx32** [Jacob-Mango/DayZ-CommunityOnlineTools#149]
See Problem:
4k : https://i.imgur.com/aYWancT.jpg
1080p: https://i.imgur.com/knWhbv9.jpg

The resolution is the only difference between these screenshots. The desktop scaling (150% or 100%) has no effect.

**Comment by LieutenantMaster** [comment]
@salutesh Do you know what should be done to make any UI work in 4k ?

**Comment by lava76** [comment]
The screenshot already shows what needs to be done since ItemSet spawner looks correct.

**Comment by LieutenantMaster** [comment]
In theory should be fixed for most modules in the next update
