### ISSUE TITLE
Crash game with object spawner by object itemOptics_base

### ISSUE THREAD

**Issue by Roofdoc13** [Jacob-Mango/DayZ-CommunityOnlineTools#152]
We are crashing when searching the word optics. at first i was thinking it was to do with the item itself but it only shows on COT i tried searching on VPP to replicate the crashing and that doesn't show in the list of options. it doesn't seem like a big deal at first but when we search optics it is at the top of the list so we immediately crash

**Comment by Zynph** [comment]
Yes, please fix this, this is very annoying...

**Comment by LieutenantMaster** [comment]
Fixed with the latest update
