### ISSUE TITLE
Leaving Spectate-Mode Bug

### ISSUE THREAD

**Issue by Shivacho** [Jacob-Mango/DayZ-CommunityOnlineTools#155]
Hello
When we leave the Spectate mode, the inventory menu partially does not work anymore--when pressing the tab key--or we are swimming in our base. We have to log out and log in again to get the menu to work again. Is there something we are doing wrong or is this a bug?

**Comment by LieutenantMaster** [comment]
Cant reproduce so far

**Comment by Shivacho** [comment]
With time it got better, the problem had occurred during a server reinstall. Thanks

**Comment by Shivacho** [comment]
Other question: Is it possible to show the input field with the red dot completely, it is the bar with set quantity and health where half covers.
<img width="649" alt="image" src="https://github.com/Jacob-Mango/DayZ-CommunityOnlineTools/assets/132194817/4d8cce05-0bad-4ace-85da-0ea50786b526">
Thanks for your great job!!

**Comment by LieutenantMaster** [comment]
Looks like a resolution issue. Let me guess, you have a 4K monitor ?

I'll have a look when I can, we have a "similar" issue for other modules where scaling kinda gives up

**Comment by Shivacho** [comment]
Yes I have a 4k monitor, would be great if you could refresh that, I think it generates a lot of work. It works as it is is.... Thanks again for the great mod and your help..
