### ISSUE TITLE
Crashes Crashes Crashes

### ISSUE THREAD

**Issue by BlackLizard88** [Jacob-Mango/DayZ-CommunityOnlineTools#161]
The last 3 updates have repeatedly caused abrupt game crashes when using the tool. But since the last Update there have been 10 game abandonments in one hour and that for every team member. And yes, we have good PCs and a very good internet connection. Can u please fix these problems. We love your Mod and we are thankful for that, its a great Tool for supporting Players on our Server, but the many crashes make our work almost impossible. So many crashes only opening the menu. Many server owners complain about the same problem. Would it perhaps be better to upload the previous version until the crash problems have been solved?
Unfortunately, we can no longer work with the tool like this in the long term - it just causes frustration.

**Comment by LieutenantMaster** [comment]
fixed
