### ISSUE TITLE
VEhicle list will only display one vehicle.

### ISSUE THREAD

**Issue by BPGoreng** [Jacob-Mango/DayZ-CommunityOnlineTools#162]
As the title says, Vehicle list displays only one vehicle at a time.   Also, a expansion covered vehicle won't display until uncovered.  I have confirmed that there are many vehicles on the server.    Vehicle mods include Expansion and RaG Vehicles.   I will do some more testing to try and help narrow down the issue.

**Comment by LieutenantMaster** [comment]
fixed
