### ISSUE TITLE
Item spawner and Vehicle spawner do not work. Just empty lists.

### ISSUE THREAD

**Issue by ghost** [Jacob-Mango/DayZ-CommunityOnlineTools#164]
Item spawner and Vehicle spawner do not work. Just empty lists.
![20240225215507_1](https://github.com/Jacob-Mango/DayZ-CommunityOnlineTools/assets/15063395/757bc7fe-5292-4d2c-8c8e-baade91554fe)
![20240225215526_1](https://github.com/Jacob-Mango/DayZ-CommunityOnlineTools/assets/15063395/aaa7e7c3-e0ed-48b8-bca7-7992850b764f)

**Comment by LieutenantMaster** [comment]
Regenerate your sets, this is usually a sign of them being broken

**Comment by ghost** [comment]
Not entirely true, if we delete CommunityOnlineTools in the profiles and start the server, then everything is okay. Then we turn off the server again and restore the deleted CommunityOnlineTools, then we start the server and everything is fine. I compared the files, there are no changes. Also in the profiles a file is created in the /CommunityOnlineTools/Logs category and it is empty, but it is empty if the server is running on Linux; on Windows logs are written normally. Why is that? I don't know.
