### ISSUE TITLE
Is there a Linux server version available?

### ISSUE THREAD

**Issue by skywalkerscott** [Jacob-Mango/DayZ-CommunityOnlineTools#169]
I have try install this mod on Linux Server, but it's can't work, maybe I did not configured right?

**Comment by Moondarker** [comment]
Inside the mod folder, rename `Addons` to `addons`, and within it, rename all pbos to lower-case (`GUI.pbo` -> `gui.pbo`, `Objects_Debug.pbo` -> `objects_debug.pbo`, `Scripts.pbo` -> `scripts.pbo`), same goes for file signatures (`.bisign` files)

**Comment by skywalkerscott** [comment]
> Inside the mod folder, rename `Addons` to `addons`, and within it, rename all pbos to lower-case (`GUI.pbo` -> `gui.pbo`, `Objects_Debug.pbo` -> `objects_debug.pbo`, `Scripts.pbo` -> `scripts.pbo`), same goes for file signatures (`.bisign` files)

I will try this later, thanks for tips.
