### ISSUE TITLE
New Error?

### ISSUE THREAD

**Issue by WilksCheckov1** [Jacob-Mango/DayZ-CommunityOnlineTools#170]
MONOLITHHOSTING, 18.06 2024 19:16:32
NULL pointer to instance
Class:      'JMTeleportModule'
Function: 'Server_Location'
Stack trace:
JM/COT/Scripts/5_Mission/communityonlinetools\modules\teleport\jmteleportmodule.c:473
JM/COT/Scripts/5_Mission/communityonlinetools\modules\teleport\jmteleportmodule.c:493
JM/COT/Scripts/5_Mission/communityonlinetools\modules\teleport\jmteleportmodule.c:213
JM/CF/Scripts/4_World/communityframework\module\deprecated\jmmodulebase.c:84
JM/CF/Scripts/3_Game/communityframework\module\cf_modulegameevent.c:18
JM/CF/Scripts/3_Game/communityframework\module\cf_modulegamemanager.c:33
JM/CF/Scripts/3_Game/communityframework\game\dayzgame.c:87
MetroRadClient/Scripts/3_Game/dayzgame.c:7
MolotovClient/Scripts/3_Game/ ssve601f \  .{22877a6d-37a1-461a-91b0-dbda5aaebc99}\com5.c:9

I have been encountering this error specifically when teleporting using the map in COT or closing out the map by hitting the x button. Teleportation via the teleport location menu works fine.

**Comment by LieutenantMaster** [comment]
Your teleport json file is from the old version, delete it and it will be fixed
