### ISSUE TITLE
Admin.Player.Godmode 2 issue

### ISSUE THREAD

**Issue by Przedek1** [Jacob-Mango/DayZ-CommunityOnlineTools#171]
Despite selected permission, players cannot turn on godmode
The option is visible, but when clicked, nothing changes

![image](https://github.com/Jacob-Mango/DayZ-CommunityOnlineTools/assets/86448494/10a470a8-04f4-4022-aca1-38961497cc25)

**Comment by lava76** [comment]
Check the individual permissions of the player (`PermissionsFramework\Permissions\<UID>.txt`). I would also strongly recommend against giving the default "everyone" role any permissions other than 0.
