### ISSUE TITLE
Severe Fog and Constant rain post update 7/24/2024

### ISSUE THREAD

**Issue by TacticalBacon-commits** [Jacob-Mango/DayZ-CommunityOnlineTools#172]
To preface I do not represent the admin team of DayZUnderground but we use your mod, post update (my mod updated at 9 am EST) and since while playing there has been constant rain, first without clouds, then with storm clouds, and on restart (see this link https://imgur.com/a/BKPy7Cj ) Fog is so severe that you can not see past 65-70 meters.

I was content to think it was just quirky weather but the fog on restart points to a possible issue with the COT update or an interaction with another mod we use. We repack mods on DUG so I am not 100% sure what conflict could exist. Hope to hear back from you.

**Comment by lava76** [comment]
This should be resolved after the 7/25/2024 update, but you may need to reset your weather one time. A non-destructive way to do that is via cfgweather.xml, i.e. if you currently have `enable="1"` in cfgweather, `set enable="0"`, restart server, set `reset="1" enable="1"`, restart server, then you can turn it off again if you don't use it.
