### ISSUE TITLE
Strange fault

### ISSUE THREAD

**Issue by Bastelbude-create** [Jacob-Mango/DayZ-CommunityOnlineTools#176]
hello. there is a bug when you use COT with this mod h**ps:/lbmaster.de/product.php?id=25 (TB Basic Needs) that you can no longer control COT with the mouse. the mouse pointer keeps jumping to the center of the screen when I want to select from the spawn menu, for example.
to be more specific: the main menu is normally there when activated. only in the submenus, i.e. where you spawn items etc. the mouse pointer always jumps out and into the center of the screen.
so you can't click on any function in the submenus, or search for items by entering text.

**Comment by LieutenantMaster** [comment]
Hello, we do not provide support to paid mods. It will be up to them to figure it out and solve it themselves
