### ISSUE TITLE
Since 1.0 - Teleport List empties on restart of server

### ISSUE THREAD

**Issue by Wizbaggd** [Jacob-Mango/DayZ-CommunityOnlineTools#30]
As the title says, every time my server restarts, it completely dumps the contents of the Teleports List json

**Comment by Da0ne** [comment]
Yea issues with Serialization, does not read/write properly. There is currently a size cap of i think 16kb to write. And by looking at the exe, theres also a limit on how many files you can write in the $profile and $saves
