### ISSUE TITLE
[Feature Request] Toggling on/off "admin mode" to be able to play without using COT.

### ISSUE THREAD

**Issue by GrosTon1** [Jacob-Mango/DayZ-CommunityOnlineTools#38]
Hey,

The title pretty says it all, I think it would be cool to have a way to toggle on/off the tools so they're not used unpurposely.
Are PRs welcome ? I'd be more than happier to contribute. If so, how should I implement this system ? Another keybind ?

**Comment by Peinful** [comment]
Not sure if this is possible, I'd recommend just rebinding the Y + H key functions to a different key.

**Comment by GrosTon1** [comment]
That would be as simple as a new boolean variables and a couple of conditions.

**Comment by Jacob-Mango** [comment]
Feel free to make a pull request if you feel you can make it in a good way. I'll inspect the changes.
