### ISSUE TITLE
[Feature Request] Close free cam wihout teleport

### ISSUE THREAD

**Issue by Catsy73** [Jacob-Mango/DayZ-CommunityOnlineTools#43]
It could be useful to be able to close the free cam without teleport at cursor.
For example, we could have a key binding like a Shift + Insert to close without teleport.

**Comment by GrosTon1** [comment]
+1, I can make a PR to do so if Jacob dont mind and don't planned it.

**Comment by exm316** [comment]
There is a quick work around, spectate yourself and then unspectate then all sorted.... No teleport!

**Comment by Catsy73** [comment]
Yes but it's a lot more complex...
