### ISSUE TITLE
Extremely slow freecam

### ISSUE THREAD

**Issue by tunneIrat** [Jacob-Mango/DayZ-CommunityOnlineTools#47]
Encountered a bug using freecam teleportation (insert)
First use is always fine, but then after first/second use, it suddenly slows down to extremely slow speeds making freecam useless.
The only way to fix it at that point have been to relog the server :/

**Comment by TheRedfoox** [comment]
Have you tried scrolling the mouse wheel ? It controls the speed of the freecam or speccam

**Comment by tunneIrat** [comment]
That actually worked.
Can't believe i didn't think about trying that.
:roll_eyes: :laughing:

**Comment by TheRedfoox** [comment]
I think you can close your issue now 😂

**Comment by Jacob-Mango** [comment]
I've personally experienced a similar issue with reproducibility steps oddly similar to this one. I'll keep it up just in case.
