### ISSUE TITLE
Disabling debug monitor.

### ISSUE THREAD

**Issue by NeoDichotomy** [Jacob-Mango/DayZ-CommunityOnlineTools#48]
Our players mostly like the debug monitor and as such we have it enabled.
However there are a noticeable chunk that would prefer it was not there.
If possible we'd like for there to be an option for it in game, something we can allow players access to so that they can simple disable or enable the monitor.
Thanks in advance for any help and for the awesome mod as it is!

**Comment by LieutenantMaster** [comment]
Wont do, this is too much of a niche request since most servers keep the debug monitor disabled.
