### ISSUE TITLE
[Request] COT functions are by default for users with rights

### ISSUE THREAD

**Issue by Sileed** [Jacob-Mango/DayZ-CommunityOnlineTools#60]
You already have the END key toggle to turn it off/on.  Would be great to have the default be off, many times the H key is pressed accidentally and you end up doing something stupid :)

**Comment by Jacob-Mango** [comment]
Couldn't figure out how to assign on mobile github but was going to do that for you. It's simple anyway, just flip the boolean where ever it is.

**Comment by GrosTon1** [comment]
Done in https://github.com/Jacob-Mango/DayZ-CommunityOnlineTools/commit/8c1ae76c561a0f302f3226052920070031ac82cb.
