### ISSUE TITLE
Community-Online-Tools do not work

### ISSUE THREAD

**Issue by oFeKeTe** [Jacob-Mango/DayZ-CommunityOnlineTools#64]
Does not work
X Ray
item set spawner
Vehicle Spawner
Map
Repair Transport
Delete on cursor
Killfeed settings no open
Thxx :)

**Comment by GrosTon1** [comment]
X-Ray, Item Set Spawner, Vehicle Spawner, Map, Delete on Cursor are working.
Killfeed settings isn't a part of the core Community Online Tools.
Repair transport may be broken as of 1.03, do you have reproduction steps ?

**Comment by ElCanu** [comment]
menu just doesn't open, i can toggle on/off but menu won't open

**Comment by GrosTon1** [comment]
This is an issue in your installation, the menu is working fine in 1.03

**Comment by TownCountry** [comment]
> X-Ray, Spawner conjunto de itens, Spawner de veículos, Mapa, Excluir no cursor estão funcionando. 
> As configurações do Killfeed não fazem parte das principais ferramentas on-line da comunidade. 
> O transporte de reparo pode ser quebrado a partir de 1.03, você tem etapas de reprodução?

How do I show you?

**Comment by Jacob-Mango** [comment]
@ElCanu @TownCountry need more information.

**Comment by Leah-Snow** [comment]
Everything works except for: XRay, Item Set Spawner, Vehicle Spawner, Map, Repair Transport
There is no error. These just don't open.

**Comment by lonewolfss** [comment]
would love a fix for  Vehicle Spawner guys i used to beable to add my vehicles in and see them in the admin menu now i only see 3 there mods been like this for a long time

**Comment by JerryAtricks** [comment]
It crashes my game when I go into Object Spawner > Firearms, and then start scrolling through the weapons. I'm not sure if it's a certain weapon doing it or the fact that I'm just in the menu scrolling. 

DayZ has exited in an unusual manner with exit code: 0xC0000005 - Status_Access_Violation
