### ISSUE TITLE
no item preview

### ISSUE THREAD

**Issue by Distur1ed** [Jacob-Mango/DayZ-CommunityOnlineTools#67]
Hello, Jacob, I would like to ask you why you removed There is no item preview in Menu Objects Spawner

**Comment by Thurston00** [comment]
Hello,

As we've said to you countless times, it isn't a big priority to us currently. It was broken in the 1.02 update months ago, and although we have gotten it working in other projects, we haven't been able to successfully get it working properly in COT.

We've told you this multiple times in the past, it'll be done when it's done.
