### ISSUE TITLE
Scroll wheel affects free cam speed even when not in free cam

### ISSUE THREAD

**Issue by ClintonButler** [Jacob-Mango/DayZ-CommunityOnlineTools#68]
Free cam speed is still adjusted when scrolling the mouse wheel while not in the Free Cam Mode, so if you are in your inventory and scroll a whole lot, then go into free cam, you can be either lightning fast or sluggish slow to move

**Comment by LieutenantMaster** [comment]
Not fully fixed but good enough in my eyes
