### ISSUE TITLE
A map update request and a spawner rotation feature on spawning buildings

### ISSUE THREAD

**Issue by Sadromus** [Jacob-Mango/DayZ-CommunityOnlineTools#69]
Have a few ideas to consider;
Updating the map image used to include english as well as the original texts. Would save some of us from having to reference another computer rendering to describe where a location is. (And for those of us who have a bad memory for names. lol)

And adding to the the item spawner for buildings the ability to set the rotation of a building to set the direction something is facing when spawned in.

**Comment by LieutenantMaster** [comment]
1) Done

2) Wont do
