### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by harleenquinn** [Jacob-Mango/DayZ-CommunityOnlineTools#72]
Bugs i've found in COT so far:
You enter the server then it opens the menu (END later Y), it works, after a few seconds it randomly stops working, nor does the menu open anymore...
Players entering with active COT may be given Admin powers
All names are blank in the players list (including my own name that is set up in steamid.txt or steamid.json)

(I enter the game, press End (active COT), press Y, the menu opens, I call Esp, spawn objects, press Y again the menu closes, I'm walking, playing, doing anything, ESP information disappears from the screen, then i Press Y to open the menu, it does nothing, it does not open anymore, it simply stops working, this is usually happening when the server is with more players.

And in the Permissions folder, almost all players who join in server, COT is creating admin permissions for them, generating steamids.txt
When the server is empty, or just I on the server, everything works flawlessly, beautifully!)

**Comment by MetropolisRL** [comment]
I ran into the same bug with displaying names in player management, names will just disappear after a while including my own.
