### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by FPS-86** [Jacob-Mango/DayZ-CommunityOnlineTools#73]
Hey!

NULL pointer to instance. Variable 'Data'
Class:      'PlayerModule'
Function: 'SetPermissions'
Stack trace:
JM/COT/Scripts/5_Mission/communityonlinetools\modules\player\playermodule.c:811
JM/CF/Scripts/3_Game/communityframework\rpc\rpcmanager.c:244
scripts/3_Game/dayzgame.c:2231

NULL pointer to instance
Class:      'AuthPlayer'
Function: 'UpdatePlayerData'
Stack trace:
JM/COT/Scripts/4_World/communityonlinetools\permissions-framework\authplayer.c:71
JM/COT/Scripts/5_Mission/communityonlinetools\communityonlinetools.c:106
scripts/3_Game/dayzgame.c:2189

**Comment by LieutenantMaster** [comment]
fixed
