### ISSUE TITLE
C.O.T now gives randoms admin level permissions

### ISSUE THREAD

**Issue by NeoDichotomy** [Jacob-Mango/DayZ-CommunityOnlineTools#79]
It seems that now random players are having 2 files created.
1 file is a text file with seemingly random characters in it and the other is a json file.
The one thing these files have in common is that they both have the permissions text in them but only the json has any permissions set to 2 like full admin map use. 
As an example file uv5vzkbDdZECW1pGTTDE7F3vaboHcztl3lRYOk_Jl1Y.txt has all the permissions zero'd.

The json files im finding might be left over from last patch, i'll keep an eye on it today and update if its still making them.
I've included a screenshot of the random character text files.
![image](https://user-images.githubusercontent.com/46833151/64911245-25b93a00-d6ed-11e9-881a-723da621813a.png)

**Comment by GrosTon1** [comment]
Jacob reverted **both** CF and COT to working versions.
