### ISSUE TITLE
CoT is intermittently loading

### ISSUE THREAD

**Issue by TaediousContagion** [Jacob-Mango/DayZ-CommunityOnlineTools#81]
I just did a fresh installation from the ground up of CoT.  I logged in and everything seemed to be working fine.  When I opened player management my frames dropped to 0.  I did hear of a fix with right clicking player management to get your frames back.  I went into freecam mode after that and I could not exit freecam mode..Had to relog.  Now I logged back in after the freecam issue and CoT won't open.  Pressing End does nothing, and when I press insert is repeatedly tells me that CoT has been toggled off.  I have relogged several times and it won't load by pressing END and insert still tells me it has been toggled off.

**Comment by GrosTon1** [comment]
There are known issues when relogging. Please close completly your game and start it again to avoid those.

**Comment by TaediousContagion** [comment]
I have done that several time. Same issue after clean load

**Comment by TaediousContagion** [comment]
also I just looked in the PermissionsFramework/Permissions folder and my steam64 id txt file is gone now.  same thing for my json in PermissionsFramework/Players.  I just did a completely fresh install of CoT and added only the 4 admin json and txt file.  Now my files are gone

**Comment by TaediousContagion** [comment]
I put my files back in to the server and restarted. Now it says that the menu is toggled on but pressing Y doesn't open the menu.  I tried changing keybinds...same issue

**Comment by GrosTon1** [comment]
Jacob reverted **both** CF and COT to working versions.
