### ISSUE TITLE
Mouse Pointer issue

### ISSUE THREAD

**Issue by MetropolisRL** [Jacob-Mango/DayZ-CommunityOnlineTools#83]
Mouse pointer not properly placed on the buttons.

![adasdd](https://user-images.githubusercontent.com/52295774/64968420-6ad29d00-d8a2-11e9-834a-f98ff3c152e6.png)

**Comment by Jacob-Mango** [comment]
Won't fix until the new version of COT is release. Not a problem. Buttons behave the same.

**Comment by LieutenantMaster** [comment]
Fixed for what is related to COT. You can still be subject to this bug but it would affect the UI for the base game and every modded UI.
