### ISSUE TITLE
Some issues with the vehicle spawner

### ISSUE THREAD

**Issue by davidp234** [Jacob-Mango/DayZ-CommunityOnlineTools#84]
When attempting to spawn in the S120 the server crashes. Can this be remove this from the list? (for now) 

The UtilityVehicle spawns a car battery in your hands can this be fixed?

The CivilianVan, V3S_Cargo_Blue and V3S_Chassis_Blue do not spawn but also do not crash the server could these be removed from the config file?

**Comment by LieutenantMaster** [comment]
fixed
