### ISSUE TITLE
Spawn points

### ISSUE THREAD

**Issue by raxto** [Jacob-Mango/DayZ-CommunityOnlineTools#85]
Is it possible to add ability to display spawn points/areas in buildings ?

Something like this: [https://www.dayztv.com/wp-content/uploads/2017/05/dayz-beta-new-loot-placement-system-vs-old-one-1.jpg](https://www.dayztv.com/wp-content/uploads/2017/05/dayz-beta-new-loot-placement-system-vs-old-one-1.jpg)

It was in Status Report - 16 May 2017
https://steamcommunity.com/games/221100/announcements/detail/1958348777674194261?l=en

**Comment by PR9INICHEK** [comment]
https://cdn.discordapp.com/attachments/499468381960011797/620860996126244874/unknown.png

**Comment by raxto** [comment]
omg, thats it. :)

**Comment by LieutenantMaster** [comment]
dayz introduced it officially in dayz diag
