### ISSUE TITLE
Issue with Crashing the Game on certain items 

### ISSUE THREAD

**Issue by BlueSkyHusky** [Jacob-Mango/DayZ-CommunityOnlineTools#87]
It seems like since the last DayZ Update to 1.06 when you scroll trough the Items the game Freezes and Crashes at a certain point. i was unable to track the items down.

**Comment by GravityWolfNotAmused** [comment]
Hello @Gronkhou,

This is sadly an issue with DayZ, and I have reported it to them. You can find my feedback tracker ticket here: https://feedback.bistudio.com/T147240

**Comment by LieutenantMaster** [comment]
fixed
