### ISSUE TITLE
Selection of items

### ISSUE THREAD

**Issue by rosazuckerfee** [Jacob-Mango/DayZ-CommunityOnlineTools#92]
Hey,
2 things:

**1:** 
is it possible to bring back the specific selection of items?
like it was before the expansion update. that you have the checkboxes. but for every item. not only for the players

**2:**
is it possible (for the default settings) to remove all the hooks from the xray selection?

**Comment by lava76** [comment]
This should be closed imo as it's waaay out of date and has been adressed long ago.
