### ISSUE TITLE
ESP Item Removal not Working.

### ISSUE THREAD

**Issue by Aeryes** [Jacob-Mango/DayZ-CommunityOnlineTools#94]
When in the ESP menu, you can no longer click on an object and delete the selcted object.

**Comment by gumbymn** [comment]
I can't even select the object, or narrow it to specific categories in ESP.

**Comment by Jacob-Mango** [comment]
Click the dropdown arrow to see more information within the ESP box. Scroll down the list and you will see the delete button.
